package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codCliente;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String direccion;
     private int estado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Garaje> garajes = new HashSet<Garaje>(0);
     private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);
     private Set<Registro> registros = new HashSet<Registro>(0);

    public Cliente() {
    }

	
    public Cliente(int codCliente, String nombre, int estado) {
        this.codCliente = codCliente;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Cliente(int codCliente, Usuario usuario, String nombre, String apellido, String direccion, int estado, Set<Usuario> usuarios, Set<Garaje> garajes, Set<Reservacion> reservacions, Set<Registro> registros) {
       this.codCliente = codCliente;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.estado = estado;
       this.usuarios = usuarios;
       this.garajes = garajes;
       this.reservacions = reservacions;
       this.registros = registros;
    }
   
    public int getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(int codCliente) {
        this.codCliente = codCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Garaje> getGarajes() {
        return this.garajes;
    }
    
    public void setGarajes(Set<Garaje> garajes) {
        this.garajes = garajes;
    }
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }


	@Override
	public String toString() {
		return "Cliente [codCliente=" + codCliente + ", usuario=" + usuario
				+ ", nombre=" + nombre + ", apellido=" + apellido
				+ ", direccion=" + direccion + ", estado=" + estado
				+ ", usuarios=" + usuarios + ", garajes=" + garajes
				+ ", reservacions=" + reservacions + ", registros=" + registros
				+ "]";
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((apellido == null) ? 0 : apellido.hashCode());
		result = prime * result + codCliente;
		result = prime * result
				+ ((direccion == null) ? 0 : direccion.hashCode());
		result = prime * result + estado;
		result = prime * result + ((garajes == null) ? 0 : garajes.hashCode());
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		result = prime * result
				+ ((registros == null) ? 0 : registros.hashCode());
		result = prime * result
				+ ((reservacions == null) ? 0 : reservacions.hashCode());
		result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
		result = prime * result
				+ ((usuarios == null) ? 0 : usuarios.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente other = (Cliente) obj;
		if (apellido == null) {
			if (other.apellido != null)
				return false;
		} else if (!apellido.equals(other.apellido))
			return false;
		if (codCliente != other.codCliente)
			return false;
		if (direccion == null) {
			if (other.direccion != null)
				return false;
		} else if (!direccion.equals(other.direccion))
			return false;
		if (estado != other.estado)
			return false;
		if (garajes == null) {
			if (other.garajes != null)
				return false;
		} else if (!garajes.equals(other.garajes))
			return false;
		if (nombre == null) {
			if (other.nombre != null)
				return false;
		} else if (!nombre.equals(other.nombre))
			return false;
		if (registros == null) {
			if (other.registros != null)
				return false;
		} else if (!registros.equals(other.registros))
			return false;
		if (reservacions == null) {
			if (other.reservacions != null)
				return false;
		} else if (!reservacions.equals(other.reservacions))
			return false;
		if (usuario == null) {
			if (other.usuario != null)
				return false;
		} else if (!usuario.equals(other.usuario))
			return false;
		if (usuarios == null) {
			if (other.usuarios != null)
				return false;
		} else if (!usuarios.equals(other.usuarios))
			return false;
		return true;
	}

    


}


