package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Garaje generated by hbm2java
 */
public class Garaje  implements java.io.Serializable {


     private int codGaraje;
     private Cliente cliente;
     private String descripcion;
     private int numParqueos;
     private Integer numPisos;
     private String distancia;
     private String tiempo;
     private Set<Registro> registros = new HashSet<Registro>(0);
     private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);
     private Set<Parqueo> parqueos = new HashSet<Parqueo>(0);

    public Garaje() {
    }

	
    public Garaje(int codGaraje, int numParqueos) {
        this.codGaraje = codGaraje;
        this.numParqueos = numParqueos;
    }
    public Garaje(int codGaraje, Cliente cliente, String descripcion, int numParqueos, Integer numPisos, Set<Registro> registros, Set<Reservacion> reservacions, Set<Parqueo> parqueos) {
       this.codGaraje = codGaraje;
       this.cliente = cliente;
       this.descripcion = descripcion;
       this.numParqueos = numParqueos;
       this.numPisos = numPisos;
       this.registros = registros;
       this.reservacions = reservacions;
       this.parqueos = parqueos;
    }
   
    public int getCodGaraje() {
        return this.codGaraje;
    }
    
    public void setCodGaraje(int codGaraje) {
        this.codGaraje = codGaraje;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getNumParqueos() {
        return this.numParqueos;
    }
    
    public void setNumParqueos(int numParqueos) {
        this.numParqueos = numParqueos;
    }
    public Integer getNumPisos() {
        return this.numPisos;
    }
    
    public void setNumPisos(Integer numPisos) {
        this.numPisos = numPisos;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }
    public Set<Parqueo> getParqueos() {
        return this.parqueos;
    }
    
    public void setParqueos(Set<Parqueo> parqueos) {
        this.parqueos = parqueos;
    }


	public String getDistancia() {
		return distancia;
	}


	public void setDistancia(String distancia) {
		this.distancia = distancia;
	}


	public String getTiempo() {
		return tiempo;
	}


	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}


	@Override
	public String toString() {
		return "Garaje [codGaraje=" + codGaraje + ", cliente=" + cliente
				+ ", descripcion=" + descripcion + ", numParqueos="
				+ numParqueos + ", numPisos=" + numPisos + ", distancia="
				+ distancia + ", tiempo=" + tiempo + ", registros=" + registros
				+ ", reservacions=" + reservacions + ", parqueos=" + parqueos
				+ "]";
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		return prime * codGaraje;
		/*int result = 1;
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result + codGaraje;
		result = prime * result
				+ ((descripcion == null) ? 0 : descripcion.hashCode());
		result = prime * result
				+ ((distancia == null) ? 0 : distancia.hashCode());
		result = prime * result + numParqueos;
		result = prime * result
				+ ((numPisos == null) ? 0 : numPisos.hashCode());
		result = prime * result
				+ ((parqueos == null) ? 0 : parqueos.hashCode());
		result = prime * result
				+ ((registros == null) ? 0 : registros.hashCode());
		result = prime * result
				+ ((reservacions == null) ? 0 : reservacions.hashCode());
		result = prime * result + ((tiempo == null) ? 0 : tiempo.hashCode());
		return result;*/
	}


	@Override
	public boolean equals(Object o) {
		
		if (o instanceof Garaje) {
		    Garaje p = (Garaje)o;
		    return this.codGaraje == p.codGaraje;
		  } else {
		    return false;
		  }
		
		/*if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Garaje other = (Garaje) obj;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (codGaraje != other.codGaraje)
			return false;
		if (descripcion == null) {
			if (other.descripcion != null)
				return false;
		} else if (!descripcion.equals(other.descripcion))
			return false;
		if (distancia == null) {
			if (other.distancia != null)
				return false;
		} else if (!distancia.equals(other.distancia))
			return false;
		if (numParqueos != other.numParqueos)
			return false;
		if (numPisos == null) {
			if (other.numPisos != null)
				return false;
		} else if (!numPisos.equals(other.numPisos))
			return false;
		if (parqueos == null) {
			if (other.parqueos != null)
				return false;
		} else if (!parqueos.equals(other.parqueos))
			return false;
		if (registros == null) {
			if (other.registros != null)
				return false;
		} else if (!registros.equals(other.registros))
			return false;
		if (reservacions == null) {
			if (other.reservacions != null)
				return false;
		} else if (!reservacions.equals(other.reservacions))
			return false;
		if (tiempo == null) {
			if (other.tiempo != null)
				return false;
		} else if (!tiempo.equals(other.tiempo))
			return false;
		return true;
		*/
	}

	


}


