package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA



/**
 * Publicidad generated by hbm2java
 */
public class Publicidad {


     private int codPublicidad;
     private LocalComercial localComercial;
     private String imagen;
     private String fecha_registro;
     private String fecha_vencimiento;
     private int estado;

    public Publicidad() {
    }

	public int getCodPublicidad() {
		return codPublicidad;
	}

	public void setCodPublicidad(int codPublicidad) {
		this.codPublicidad = codPublicidad;
	}

	public LocalComercial getLocalComercial() {
		return localComercial;
	}

	public void setLocalComercial(LocalComercial localComercial) {
		this.localComercial = localComercial;
	}

	public String getImagen() {
		return imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public String getFecha_registro() {
		return fecha_registro;
	}

	public void setFecha_registro(String fecha_registro) {
		this.fecha_registro = fecha_registro;
	}

	public String getFecha_vencimiento() {
		return fecha_vencimiento;
	}

	public void setFecha_vencimiento(String fecha_vencimiento) {
		this.fecha_vencimiento = fecha_vencimiento;
	}

	@Override
	public String toString() {
		return "Publicidad [codPublicidad=" + codPublicidad
				+ ", localComercial=" + localComercial + ", imagen=" + imagen
				+ ", estado=" + estado + ", fecha_registro=" + fecha_registro
				+ ", fecha_vencimiento=" + fecha_vencimiento + "]";
	}
    

}


