package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private int codReservacion;
     private Garaje garaje;
     private Parqueo parqueo;
     private Cliente cliente;
     private Date fechaRegistro;
     private String fechaReservacion;
     private int estado;

    public Reservacion() {
    }

	
    public Reservacion(int codReservacion, Date fechaRegistro, int estado) {
        this.codReservacion = codReservacion;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
    }
    public Reservacion(int codReservacion, Garaje garaje, Parqueo parqueo, Cliente cliente, Date fechaRegistro, String fechaReservacion, int estado) {
       this.codReservacion = codReservacion;
       this.garaje = garaje;
       this.parqueo = parqueo;
       this.cliente = cliente;
       this.fechaRegistro = fechaRegistro;
       this.fechaReservacion = fechaReservacion;
       this.estado = estado;
    }
   
    public int getCodReservacion() {
        return this.codReservacion;
    }
    
    public void setCodReservacion(int codReservacion) {
        this.codReservacion = codReservacion;
    }
    public Garaje getGaraje() {
        return this.garaje;
    }
    
    public void setGaraje(Garaje garaje) {
        this.garaje = garaje;
    }
    public Parqueo getParqueo() {
        return this.parqueo;
    }
    
    public void setParqueo(Parqueo parqueo) {
        this.parqueo = parqueo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getFechaReservacion() {
        return this.fechaReservacion;
    }
    
    public void setFechaReservacion(String fechaReservacion) {
        this.fechaReservacion = fechaReservacion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


