package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LocalComercialTipo generated by hbm2java
 */
public class LocalComercialTipo  implements java.io.Serializable {


     private int codLocComTipo;
     private LocalComercial localComercial;
     private String descripcion;
     private Set<LocalComercial> localComercials = new HashSet<LocalComercial>(0);

    public LocalComercialTipo() {
    }

	
    public LocalComercialTipo(int codLocComTipo, String descripcion) {
        this.codLocComTipo = codLocComTipo;
        this.descripcion = descripcion;
    }
    public LocalComercialTipo(int codLocComTipo, LocalComercial localComercial, String descripcion, Set<LocalComercial> localComercials) {
       this.codLocComTipo = codLocComTipo;
       this.localComercial = localComercial;
       this.descripcion = descripcion;
       this.localComercials = localComercials;
    }
   
    public int getCodLocComTipo() {
        return this.codLocComTipo;
    }
    
    public void setCodLocComTipo(int codLocComTipo) {
        this.codLocComTipo = codLocComTipo;
    }
    public LocalComercial getLocalComercial() {
        return this.localComercial;
    }
    
    public void setLocalComercial(LocalComercial localComercial) {
        this.localComercial = localComercial;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<LocalComercial> getLocalComercials() {
        return this.localComercials;
    }
    
    public void setLocalComercials(Set<LocalComercial> localComercials) {
        this.localComercials = localComercials;
    }




}


