package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LocalComercial generated by hbm2java
 */
public class LocalComercial  implements java.io.Serializable {


     private int codLocalComercial;
     private LocalComercialTipo localComercialTipo;
     private String nombre;
     private int estado;
     private Set<LocalComercialTipo> localComercialTipos = new HashSet<LocalComercialTipo>(0);
     private Set<Publicidad> publicidads = new HashSet<Publicidad>(0);

    public LocalComercial() {
    }

	
    public LocalComercial(int codLocalComercial, String nombre, int estado) {
        this.codLocalComercial = codLocalComercial;
        this.nombre = nombre;
        this.estado = estado;
    }
    public LocalComercial(int codLocalComercial, LocalComercialTipo localComercialTipo, String nombre, int estado, Set<LocalComercialTipo> localComercialTipos, Set<Publicidad> publicidads) {
       this.codLocalComercial = codLocalComercial;
       this.localComercialTipo = localComercialTipo;
       this.nombre = nombre;
       this.estado = estado;
       this.localComercialTipos = localComercialTipos;
       this.publicidads = publicidads;
    }
   
    public int getCodLocalComercial() {
        return this.codLocalComercial;
    }
    
    public void setCodLocalComercial(int codLocalComercial) {
        this.codLocalComercial = codLocalComercial;
    }
    public LocalComercialTipo getLocalComercialTipo() {
        return this.localComercialTipo;
    }
    
    public void setLocalComercialTipo(LocalComercialTipo localComercialTipo) {
        this.localComercialTipo = localComercialTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<LocalComercialTipo> getLocalComercialTipos() {
        return this.localComercialTipos;
    }
    
    public void setLocalComercialTipos(Set<LocalComercialTipo> localComercialTipos) {
        this.localComercialTipos = localComercialTipos;
    }
    public Set<Publicidad> getPublicidads() {
        return this.publicidads;
    }
    
    public void setPublicidads(Set<Publicidad> publicidads) {
        this.publicidads = publicidads;
    }




}


