package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LocalComercialTipo generated by hbm2java
 */
public class LocalComercialTipo  implements java.io.Serializable {


     private int codLocComTipo;
     private String descripcion;
     private Set<LocalComercial> localComercials = new HashSet<LocalComercial>(0);
	
    public LocalComercialTipo(int codLocComTipo, String descripcion) {
        this.codLocComTipo = codLocComTipo;
        this.descripcion = descripcion;
    }
    public LocalComercialTipo(int codLocComTipo, LocalComercial localComercial, String descripcion, Set<LocalComercial> localComercials) {
       this.codLocComTipo = codLocComTipo;
       this.descripcion = descripcion;
       this.localComercials = localComercials;
    }
   
    public int getCodLocComTipo() {
        return this.codLocComTipo;
    }
    
    public void setCodLocComTipo(int codLocComTipo) {
        this.codLocComTipo = codLocComTipo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<LocalComercial> getLocalComercials() {
        return this.localComercials;
    }
    
    public void setLocalComercials(Set<LocalComercial> localComercials) {
        this.localComercials = localComercials;
    }
	@Override
	public String toString() {
		return "LocalComercialTipo [codLocComTipo=" + codLocComTipo
				+ ", descripcion=" + descripcion + ", localComercials="
				+ localComercials + "]";
	}
	@Override
	public int hashCode() {
		return this.codLocComTipo;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LocalComercialTipo other = (LocalComercialTipo) obj;
		if (codLocComTipo != other.codLocComTipo)
			return false;
		if (descripcion == null) {
			if (other.descripcion != null)
				return false;
		} else if (!descripcion.equals(other.descripcion))
			return false;
		if (localComercials == null) {
			if (other.localComercials != null)
				return false;
		} else if (!localComercials.equals(other.localComercials))
			return false;
		return true;
	}




}


