package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parqueo generated by hbm2java
 */
public class Parqueo  implements java.io.Serializable {


     private int codParqueo;
     private Garaje garaje;
     private String codDescripcion;
     private Integer piso;
     private int estado;
     private Set<Registro> registros = new HashSet<Registro>(0);
     private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);

    public Parqueo() {
    }

	
    public Parqueo(int codParqueo, String codDescripcion, int estado) {
        this.codParqueo = codParqueo;
        this.codDescripcion = codDescripcion;
        this.estado = estado;
    }
    public Parqueo(int codParqueo, Garaje garaje, String codDescripcion, Integer piso, int estado, Set<Registro> registros, Set<Reservacion> reservacions) {
       this.codParqueo = codParqueo;
       this.garaje = garaje;
       this.codDescripcion = codDescripcion;
       this.piso = piso;
       this.estado = estado;
       this.registros = registros;
       this.reservacions = reservacions;
    }
   
    public int getCodParqueo() {
        return this.codParqueo;
    }
    
    public void setCodParqueo(int codParqueo) {
        this.codParqueo = codParqueo;
    }
    public Garaje getGaraje() {
        return this.garaje;
    }
    
    public void setGaraje(Garaje garaje) {
        this.garaje = garaje;
    }
    public String getCodDescripcion() {
        return this.codDescripcion;
    }
    
    public void setCodDescripcion(String codDescripcion) {
        this.codDescripcion = codDescripcion;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }




}


