package entidades;

import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.AsyncTask;
import android.util.Log;

import com.example.spi.PublicidadAdapter;

// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA



/**
 * Publicidad generated by hbm2java
 */
public class Publicidad {


     private int codPublicidad;
     private LocalComercial localComercial;
     private String imagenURL;
     private Bitmap imagen;
     private String fecha_registro;
     private String fecha_vencimiento;
     private int estado;
     private PublicidadAdapter sta;

    public Publicidad() {
    }

	

	public int getCodPublicidad() {
		return codPublicidad;
	}



	public void setCodPublicidad(int codPublicidad) {
		this.codPublicidad = codPublicidad;
	}



	public LocalComercial getLocalComercial() {
		return localComercial;
	}



	public void setLocalComercial(LocalComercial localComercial) {
		this.localComercial = localComercial;
	}



	public String getImagenURL() {
		return imagenURL;
	}



	public void setImagenURL(String imagenURL) {
		this.imagenURL = imagenURL;
	}



	public Bitmap getImagen() {
		return imagen;
	}



	public void setImagen(Bitmap imagen) {
		this.imagen = imagen;
	}



	public String getFecha_registro() {
		return fecha_registro;
	}



	public void setFecha_registro(String fecha_registro) {
		this.fecha_registro = fecha_registro;
	}



	public String getFecha_vencimiento() {
		return fecha_vencimiento;
	}



	public void setFecha_vencimiento(String fecha_vencimiento) {
		this.fecha_vencimiento = fecha_vencimiento;
	}



	public int getEstado() {
		return estado;
	}



	public void setEstado(int estado) {
		this.estado = estado;
	}



	public PublicidadAdapter getSta() {
		return sta;
	}



	public void setSta(PublicidadAdapter sta) {
		this.sta = sta;
	}
	
	public static Bitmap getBitmapFromURL(String src) {
	    try {
	        URL url = new URL(src);
	        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
	        connection.setDoInput(true);
	        connection.connect();
	        InputStream input = connection.getInputStream();
	        Bitmap myBitmap = BitmapFactory.decodeStream(input);
	        return myBitmap;
	    } catch (IOException e) {
	        e.printStackTrace();
	        return null;
	    }
	}



	@Override
	public String toString() {
		return "Publicidad [codPublicidad=" + codPublicidad
				+ ", localComercial=" + localComercial + ", imagen=" + imagenURL
				+ ", estado=" + estado + ", fecha_registro=" + fecha_registro
				+ ", fecha_vencimiento=" + fecha_vencimiento + "]";
	}
	
	public void loadImage(PublicidadAdapter sta) {
        // HOLD A REFERENCE TO THE ADAPTER
        this.sta = sta;
        if (imagenURL != null && !imagenURL.equals("")) {
            new ImageLoadTask().execute(imagenURL);
        } else
        	System.out.println("URL no cargada");
    }
    
	// ASYNC TASK TO AVOID CHOKING UP UI THREAD
    private class ImageLoadTask extends AsyncTask<String, String, Bitmap> {
 
        @Override
        protected void onPreExecute() {
            Log.i("ImageLoadTask", "Loading image...");
        }
 
        // PARAM[0] IS IMG URL
        protected Bitmap doInBackground(String... param) {
            Log.i("ImageLoadTask", "Attempting to load image URL: " + param[0]);
            try {
                Bitmap b = getBitmapFromURL(param[0]);
                return b;
            } catch (Exception e) {
                e.printStackTrace();
                return null;
            }
        }
 
        protected void onProgressUpdate(String... progress) {
            // NO OP
        }
 
        protected void onPostExecute(Bitmap ret) {
            if (ret != null) {
                Log.i("ImageLoadTask", "Successfully loaded " + codPublicidad + " image");
                imagen = ret;
                if (sta != null) {
                    // WHEN IMAGE IS LOADED NOTIFY THE ADAPTER
                    sta.notifyDataSetChanged();
                }
            } else {
                Log.e("ImageLoadTask", "Failed to load " + codPublicidad + " image");
            }
        }
    }

}


