package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codUsuario;
     private Cliente cliente;
     private String usuarioLogin;
     private String passwordLogin;
     private int estado;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Usuario() {
    }

	
    public Usuario(int codUsuario, String usuarioLogin, String passwordLogin, int estado) {
        this.codUsuario = codUsuario;
        this.usuarioLogin = usuarioLogin;
        this.passwordLogin = passwordLogin;
        this.estado = estado;
    }
    public Usuario(int codUsuario, Cliente cliente, String usuarioLogin, String passwordLogin, int estado, Set<Cliente> clientes) {
       this.codUsuario = codUsuario;
       this.cliente = cliente;
       this.usuarioLogin = usuarioLogin;
       this.passwordLogin = passwordLogin;
       this.estado = estado;
       this.clientes = clientes;
    }
   
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getUsuarioLogin() {
        return this.usuarioLogin;
    }
    
    public void setUsuarioLogin(String usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }
    public String getPasswordLogin() {
        return this.passwordLogin;
    }
    
    public void setPasswordLogin(String passwordLogin) {
        this.passwordLogin = passwordLogin;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result
				+ ((clientes == null) ? 0 : clientes.hashCode());
		result = prime * result + codUsuario;
		result = prime * result + estado;
		result = prime * result
				+ ((passwordLogin == null) ? 0 : passwordLogin.hashCode());
		result = prime * result
				+ ((usuarioLogin == null) ? 0 : usuarioLogin.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (clientes == null) {
			if (other.clientes != null)
				return false;
		} else if (!clientes.equals(other.clientes))
			return false;
		if (codUsuario != other.codUsuario)
			return false;
		if (estado != other.estado)
			return false;
		if (passwordLogin == null) {
			if (other.passwordLogin != null)
				return false;
		} else if (!passwordLogin.equals(other.passwordLogin))
			return false;
		if (usuarioLogin == null) {
			if (other.usuarioLogin != null)
				return false;
		} else if (!usuarioLogin.equals(other.usuarioLogin))
			return false;
		return true;
	}




}


