package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA



/**
 * Publicidad generated by hbm2java
 */
public class Publicidad  implements java.io.Serializable {


     private int codPublicidad;
     private LocalComercial localComercial;
     private byte[] imagen;
     private int estado;

    public Publicidad() {
    }

	
    public Publicidad(int codPublicidad, byte[] imagen, int estado) {
        this.codPublicidad = codPublicidad;
        this.imagen = imagen;
        this.estado = estado;
    }
    public Publicidad(int codPublicidad, LocalComercial localComercial, byte[] imagen, int estado) {
       this.codPublicidad = codPublicidad;
       this.localComercial = localComercial;
       this.imagen = imagen;
       this.estado = estado;
    }
   
    public int getCodPublicidad() {
        return this.codPublicidad;
    }
    
    public void setCodPublicidad(int codPublicidad) {
        this.codPublicidad = codPublicidad;
    }
    public LocalComercial getLocalComercial() {
        return this.localComercial;
    }
    
    public void setLocalComercial(LocalComercial localComercial) {
        this.localComercial = localComercial;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


