package entidades;
// Generated 15-dic-2013 17:08:56 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private int codRegistro;
     private Garaje garaje;
     private Parqueo parqueo;
     private Cliente cliente;
     private Date fechaRegistro;
     private BigDecimal valor;

    public Registro() {
    }

	
    public Registro(int codRegistro, Date fechaRegistro) {
        this.codRegistro = codRegistro;
        this.fechaRegistro = fechaRegistro;
    }
    public Registro(int codRegistro, Garaje garaje, Parqueo parqueo, Cliente cliente, Date fechaRegistro, BigDecimal valor) {
       this.codRegistro = codRegistro;
       this.garaje = garaje;
       this.parqueo = parqueo;
       this.cliente = cliente;
       this.fechaRegistro = fechaRegistro;
       this.valor = valor;
    }
   
    public int getCodRegistro() {
        return this.codRegistro;
    }
    
    public void setCodRegistro(int codRegistro) {
        this.codRegistro = codRegistro;
    }
    public Garaje getGaraje() {
        return this.garaje;
    }
    
    public void setGaraje(Garaje garaje) {
        this.garaje = garaje;
    }
    public Parqueo getParqueo() {
        return this.parqueo;
    }
    
    public void setParqueo(Parqueo parqueo) {
        this.parqueo = parqueo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


